### PR TITLE
Implement password related functions

### PR DESCRIPTION
**Pull request by irenenguyen1017**
I've implemented the forgot password and reset password features for Front-end app.

[Trello ticket](https://trello.com/c/gQ6jpqKz/83-authentication-authorisation-related-features-for-front-end-app)

Screenshot 2023-12-12 at 12 13 27 am

Screenshot 2023-12-12 at 12 22 40 am

Screenshot 2023-12-12 at 12 22 49 am

Screenshot 2023-12-12 at 12 31 52 am

### CODE REVIEW

**Comment by ellenpham** [comment]
That looks really good. Only one minor thing you might consider to change the notice content to be more informative (depends on the password requirement) and move to the bottom, something like this?

e7560af05c9452bc77f305556e3f82617b1844ce

**Comment by irenenguyen1017** [comment]
Screenshot 2023-12-12 at 12 09 25 pm

Screenshot 2023-12-12 at 12 09 06 pm

**Comment by irenenguyen1017** [comment]
Screenshot 2023-12-12 at 12 09 36 pm

Screenshot 2023-12-12 at 12 09 25 pm

Screenshot 2023-12-12 at 12 09 06 pm

**Comment by irenenguyen1017** [comment]
@ellenpham Could you kindly fetch my branch to your local environment and test it there first next time? It's a quick process and mirrors what I usually do before reviewing other code. This approach could save us both some time. Thank you!

**Comment by ellenpham** [comment]
Sure, no worries

**Review by ellenpham — APPROVED** [review]

**Pull request merged**
