### PR TITLE
Cart Page

### PR DESCRIPTION
**Pull request by ellenpham**
Hi all, I just implemented a simple layout for cart page, I have not done the proper data and apply any logic yet, just use dummy data to test the layout.  Could you please just see if we need to change anything relating to the layout, I will make the adjustments and add the logic later?

I'll resolve the conflicts later. Just need to head out now.

### CODE REVIEW

**Comment by irenenguyen1017** [comment]
Hi Ellen, I fetched your branch and ran it locally, it looks great. However, I noticed that the layout of the Cart page differs from our wireframe. Can you confirm this?

Screenshot 2023-12-16 at 9 44 05 pm

shopping-cart-page

**Comment by ellenpham** [comment]
@irenenguyen1017 yes, I made it a bit different because when we designed we weren't sure how our data would be like. But now when we actually start the code then we know. 

The product names are short and the product image does not look nice if being set as rectangle; so if we stick to the wireframe, the cart item box will look very empty and unbalanced, so I move the total price section to the right to make the layout looks more balanced overall. 

Plus, in the wireframe, we have 2 price columns, which did not really make sense since we will make the items price increase as the quantity increases. I think it's not a big issue if we twist the layout a bit to be more user-friendly and suitable with the data we are having, as long as it does the job and look fine overall. We can always make a note in the documentation as Alex said it's flexible if you make changes when you code, just need to note to the documentation or can even mention when we do presentation. They probably just check the features mainly, the layout would not be scrutized too much.

**Comment by irenenguyen1017** [comment]
I was referring to the part of the total that you made horizontal instead of vertical. Of course, the image should not be rectangular. I'm only talking about the overall layout. We have two price columns because one is for the original price, and the other is for the total price when a user increases the quantity of that product. You can see a similar approach in large e-commerce platforms like Amazon, and I think it makes sense and is more user-friendly.

Screenshot 2023-12-16 at 10 46 29 pm

**Comment by irenenguyen1017** [comment]
However, feel free to proceed as you see fit, since you are the one designing the page. For future reference, if you choose to deviate from the wireframe, could you please include an explanation in the description? This will help us avoid any confusion and save time during our discussions. Thank you.

**Comment by ellenpham** [comment]
I'll keep that in mind. As you can see, the big site they have a lot of other info so it makes sense to include the original price to not confuse audience, but since our site does not have much info, so keeping it simple should be ok and clear enough to demonstrate our purposes. However, If you still want to add an original price, I can make one under the product names, similar to this image below. I'll also put a title bar (product, quantity, subtotal) on top of the cart items to make it more clear. 

image

**Comment by irenenguyen1017** [comment]
Following our previous discussion where you mentioned that Alex finds it acceptable to make changes during coding, please feel free to design the page as you see fit. I appreciate any explanations of changes made in advance, as this helps streamline our process. Given that we still have a significant amount of work to complete on this project, this approach will help optimize our time.

**Comment by ellenpham** [comment]
@irenenguyen1017 as mentioned, I'll keep that in mind. Thank you.

**Comment by ellenpham** [comment]
@irenenguyen1017 Btw, do you have any idea why the deployment failed? Do I need to do npm run build? Do I need to do any configuration?

**Pull request merged**
